### PR TITLE
Report log level.

### PR DESCRIPTION
**Pull request by clokep**
This matches the changes from matrix-org/synapse#8477.

### CODE REVIEW

**Comment by clokep** [comment]
Wasn't sure who to request review from, hopefully one of you is correct. 😄

**Review by neilisfragile — COMMENTED** [review]
These changes look good to merge as is.

While you are in the area could you also check if other datapoints are transmitted and not currently handled?

For instance I think count_monthly_users is an example.

For double points, if you could also add aggregation support for count_monthly_users that would be extremely helpful. https://github.com/matrix-org/panopticon/blob/master/scripts/aggregate.py it should be quite easy to crib.

No need to aggregate log level though.

**Comment by clokep** [comment]
> While you are in the area could you also check if other datapoints are transmitted and not currently handled?
> 
> For instance I think count_monthly_users is an example.

I cross-referenced and it seems `monthly_active_users` is not handled, I assume this is the same thing!

I'll add that and take a look at aggregating it.

**Comment by clokep** [comment]
@neilisfragile I think I made the proper changes, the `docker-tests.sh` pass, but I'm unsure how/if there's anyway to test the aggregation.

**Review by neilisfragile — APPROVED** [review]
LGTM, I'm afraid that the testing coverage is pretty poor though changes are generally rare  - the aggregate table will also need the mau column adding manually.

**Comment by clokep** [comment]
This was deployed and I confirmed that both new columns are having data added.

**Pull request merged**
